version: "3"

tasks:
  frontend:
    cmds:
      - git submodule add --force https://github.com/ATTACK-Workbench/attack-workbench-frontend.git
      - git submodule update --remote attack-workbench-frontend
  backend:
    cmds:
      - git submodule add --force https://github.com/ATTACK-Workbench/attack-workbench-rest-api.git
      - git submodule update --remote attack-workbench-rest-api
  build:
    dir: attack-workbench-frontend
    cmds:
      - docker compose build
  start:
    dir: attack-workbench-frontend
    cmds:
      - docker compose up -d
  stop:
    dir: attack-workbench-frontend
    cmds:
      - docker compose stop
  down:
    dir: attack-workbench-frontend
    cmds:
      - docker compose down
  logs:
    dir: attack-workbench-frontend
    cmds:
      - docker compose logs -f
  ps:
    dir: attack-workbench-frontend
    cmds:
      - docker compose ps -a
